on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to rename prefix packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello rename action step
        id: action
      #uses: ./ # Uses an action in the root directory
      #- name: Action step
       # id: rename
        uses: sfelli/byd-package-rename@main
        with:
          projects-path: './projects'
          old-prefix: 'stend'
          new-prefix: 'sixense'
      - name: Get the output time
        run: echo "The time was ${{ steps.action.outputs.time }}"